# Copyright Business Blockchain www.blockchainempresarial.com. All Rights Reserved.
# Autor: Ricardo Ruano, ricardo@blockchainempresarial.com
# Date: 20-08-2020
# SPDX-License-Identifier: Apache-2.0
#
---
    ################################################################################
    #   Section: Organizations
    ################################################################################
    Organizations:
    
        - &OrdererOrg
            Name: OrdererOrg
            ID: OrdererMSP
            MSPDir: crypto-config/ordererOrganizations/mte.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('OrdererMSP.member')"
                Writers:
                    Type: Signature
                    Rule: "OR('OrdererMSP.member')"
                Admins:
                    Type: Signature
                    Rule: "OR('OrdererMSP.admin')"
            OrdererEndpoints:
                - orderer.mte.com:7050
    
        - &udenar
            Name: udenarMSP
            ID: udenarMSP
            MSPDir: crypto-config/peerOrganizations/udenar.mte.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('udenarMSP.admin', 'udenarMSP.peer', 'udenarMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('udenarMSP.admin', 'udenarMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('udenarMSP.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('udenarMSP.peer')"
            AnchorPeers:
                - Host: peer0.udenar.mte.com
                  Port: 7051
    
        - &cesmag
            Name: cesmagMSP
            ID: cesmagMSP
            MSPDir: crypto-config/peerOrganizations/cesmag.mte.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('cesmagMSP.admin', 'cesmagMSP.peer', 'cesmagMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('cesmagMSP.admin', 'cesmagMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('cesmagMSP.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('cesmagMSP.peer')"
            AnchorPeers:
                - Host: peer0.cesmag.mte.com
                  Port: 7051
    
        - &mariana
            Name: marianaMSP
            ID: marianaMSP
            MSPDir: crypto-config/peerOrganizations/mariana.mte.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('marianaMSP.admin', 'marianaMSP.peer', 'marianaMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('marianaMSP.admin', 'marianaMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('marianaMSP.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('marianaMSP.peer')"
            AnchorPeers:
                - Host: peer0.mariana.mte.com
                  Port: 7051
        - &cooperativa
            Name: cooperativaMSP
            ID: cooperativaMSP
            MSPDir: crypto-config/peerOrganizations/cooperativa.mte.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('cooperativaMSP.admin', 'cooperativaMSP.peer', 'cooperativaMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('cooperativaMSP.admin', 'cooperativaMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('cooperativaMSP.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('cooperativaMSP.peer')"
            AnchorPeers:
                - Host: peer0.cooperativa.mte.com
                  Port: 7051
        - &hdepartamental
            Name: hdepartamentalMSP
            ID: hdepartamentalMSP
            MSPDir: crypto-config/peerOrganizations/hdepartamental.mte.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('hdepartamentalMSP.admin', 'hdepartamentalMSP.peer', 'hdepartamentalMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('hdepartamentalMSP.admin', 'hdepartamentalMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('hdepartamentalMSP.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('hdepartamentalMSP.peer')"
            AnchorPeers:
                - Host: peer0.hdepartamental.mte.com
                  Port: 7051    
    ################################################################################
    #   SECTION: Capabilities
    ################################################################################
    Capabilities:
        Channel: &ChannelCapabilities
            V2_0: true
    
        Orderer: &OrdererCapabilities
            V2_0: true
    
        Application: &ApplicationCapabilities
            V2_0: true        
    
    ################################################################################
    #   SECTION: Application
    ################################################################################
    Application: &ApplicationDefaults
    
        # Organizations is the list of orgs which are defined as participants on
        # the application side of the network
        Organizations:
    
        # Policies defines the set of policies at this level of the config tree
        # For Application policies, their canonical path is
        #   /Channel/Application/<PolicyName>
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
            LifecycleEndorsement:
                Type: ImplicitMeta
                Rule: "ANY Endorsement" # <-- This is the default policy for channels cambiar por ANY Endorsement
            Endorsement:
                Type: ImplicitMeta
                Rule: "ANY Endorsement" # <-- This is the default policy for channels cambiar por ANY Endorsement
    
        Capabilities:
            <<: *ApplicationCapabilities    
    
    ################################################################################
    #   SECTION: Orderer
    ################################################################################
    Orderer: &OrdererDefaults
        # Orderer Type: The orderer implementation to start
        OrdererType: solo
    
    #    OrdererType: etcdraft
    
        EtcdRaft:
            Consenters:
            - Host: orderer.mte.com
              Port: 7050
              ClientTLSCert: ../organizations/ordererOrganizations/mte.com/orderers/orderer.mte.com/tls/server.crt
              ServerTLSCert: ../organizations/ordererOrganizations/mte.com/orderers/orderer.mte.com/tls/server.crt
    
        Addresses:
            - orderer.mte.com:7050
        BatchTimeout: 2s
        BatchSize:
            MaxMessageCount: 10
            AbsoluteMaxBytes: 99 MB
            PreferredMaxBytes: 512 KB
    
        Kafka:
            Brokers:
                - 127.0.0.1:9092
        Organizations:
    
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
            # BlockValidation specifies what signatures must be included in the block
            # from the orderer for the peer to validate it.
            BlockValidation:
                Type: ImplicitMeta
                Rule: "ANY Writers"
    
    ################################################################################
    #
    #   CHANNEL
    #
    #   This section defines the values to encode into a config transaction or
    #   genesis block for channel related parameters.
    #
    ################################################################################
    Channel: &ChannelDefaults
        # Policies defines the set of policies at this level of the config tree
        # For Channel policies, their canonical path is
        #   /Channel/<PolicyName>
        Policies:
            # Who may invoke the 'Deliver' API
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            # Who may invoke the 'Broadcast' API
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            # By default, who may modify elements at this config level
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
    
        # Capabilities describes the channel level capabilities, see the
        # dedicated Capabilities section elsewhere in this file for a full
        # description
        Capabilities:
            <<: *ChannelCapabilities
    
    ################################################################################
    #   Profile
    ################################################################################
    Profiles:
    
        ThreeOrgsOrdererGenesis:
            <<: *ChannelDefaults
            Orderer:
                <<: *OrdererDefaults
                Organizations:
                    - *OrdererOrg
                Capabilities:
                    <<: *OrdererCapabilities
            Consortiums:
                SampleConsortium:
                    Organizations:
                        - *udenar
                        - *cesmag
                        - *mariana
                        - *cooperativa
                        - *hdepartamental
        ThreeOrgsChannel:
            Consortium: SampleConsortium
            <<: *ChannelDefaults
            Application:
                <<: *ApplicationDefaults
                Organizations:
                    - *udenar
                    - *cesmag
                    - *mariana
                    - *cooperativa
                    - *hdepartamental
                Capabilities:
                    <<: *ApplicationCapabilities
    